call plug#begin('~/.vim/plugged')
Plug 'https://github.com/atelierbram/vim-colors_atelier-schemes'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'vim-scripts/taglist.vim'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
Plug 'vim-syntastic/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'majutsushi/tagbar'
Plug 'vim-latex/vim-latex'
Plug 'tpope/vim-surround'
call plug#end()
filetype on
"Indent Stuff
filetype indent on
set tabstop=2
set shiftwidth=2
set expandtab

"Number set up
set number
set colorcolumn=160
set tw=159
autocmd BufWritePre * :%s/\s\+$//e
set hlsearch

"Configure NerdTree
let NERDTreeMapActivateNode='<right>'
let NERDTreeShowHidden=1
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p
syntax on
filetype indent off
filetype plugin on

" Switch windows with CTRL-hjkl
noremap <C-J> <C-W><C-J>
noremap <C-K> <C-W><C-K>
noremap <C-L> <C-W><C-L>
noremap <C-H> <C-W><C-H>

" Switch tabs with F5 and F6
inoremap <F5> <ESC>:tabp<CR>i<right>
inoremap <F6> <ESC>:tabn<CR>i<right>
nnoremap <F5> :tabp<CR>
nnoremap <F6> :tabn<CR>

set showmatch  " Highlight matching braces

colorscheme Atelier_HeathDark
set cursorline " Highlight current line
:hi CursorLine cterm=underline ctermbg=none ctermfg=none
set nostartofline " Vertical movement preserves horizontal position

" -----------------------------Plugins--------------------------------------
" airline
set laststatus=2 " Always show airline
let g:airline_powerline_fonts = 1 " Use fancy arrow font
let g:airline_detect_paste=1 " Show PASTE if in paste mode
let g:airline#extensions#tabline#enabled = 1 " Show airline for tabs too
let g:airline#extensions#branch#enabled = 1

" vim-gitgutter
let g:airline#extensions#hunks#non_zero_only = 1 " In vim-airline, only display 'hunks' if the diff is non-zero
let g:gitgutter_enabled = 1

" javac for Syntastic
let g:syntastic_java_checkers = ['javac']
let g:syntastic_java_javac_config_file_enabled = 1

" C++11 for Syntastic
let g:syntastic_cpp_compiler_options = "-std=c++17"

" Syntatic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_error_symbol = '✘'
let g:syntastic_warning_symbol = "▲"
augroup mySyntastic
  au!
  au FileType tex let b:syntastic_mode = "passive"
augroup END

" Tagbar
nmap <F8> :TagbarToggle<CR>

" deocomplete
let g:deoplete#enable_at_startup = 1
