export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig/:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$HOME/.local/lib/:$LD_LIBRARY_PATH
export  C_INCLUDE_PATH=$HOME/.local/include/:$C_INCLUDE_PATH
export PATH="/usr/local/sbin:$PATH"
. "$HOME/.cargo/env"
