export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig/:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$HOME/.local/lib/:$LD_LIBRARY_PATH
export  C_INCLUDE_PATH=$HOME/.local/include/:$C_INCLUDE_PATH
export PATH="$HOME/magick/bin:/opt/nvim-linux-x86_64/bin:/usr/local/sbin:$PATH"
if ! hostname | grep "\.cloudlab\.us$" > /dev/null; then
  export PATH="$HOME/go/bin:$PATH"
  . "$HOME/.cargo/env"
  . "$HOME/.ghcup/env"
fi
export BROWSER="/mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe"
export S6="${HOME}/.local/share/s6"

# BEGIN opam configuration
# This is useful if you're using opam as it adds:
#   - the correct directories to the PATH
#   - auto-completion for the opam binary
# This section can be safely removed at any time if needed.
[[ ! -r '/home/tewaro/.opam/opam-init/init.zsh' ]] || source '/home/tewaro/.opam/opam-init/init.zsh' > /dev/null 2> /dev/null
# END opam configuration
. $HOME/.elan/env > /dev/null 2> /dev/null
export HEIMDALL_KERNEL=/var/local/adityat/LDOS/Heimdall/integration/kernel-level
export TERMINFO_DIRS="$HOME/.local/share/terminfo/:${TERMINFO_DIRS}"
