#
# .bashrc - How I configure bash
#
# This is just a skeleton; the real heavy lifting is done by various
# compartmentalized scripts, which are all sourced by this file. Inspired by
# Zach Holman's dotfiles organization.
#
# Original Author
#   Jake Zimmerman <jake@zimmerman.io>
#
# Modified By
#   Michael Murphy <mjmurphy@cmu.edu>
#

# Load a module robustly by skipping all remaining modules if any module fails
# to load
load_module() {
  if [ -n "$ABORTED" ]; then
    return
  fi

  module="$1"
  if [ -f "$module" ]; then
    source $module

    if [ "$?" != "0" ]; then
      echo "Module $module failed to load. Exiting."
      export ABORTED=1
      return
    fi
  fi
}

# Load host specific things which must happen before the interactivity check
load_module ~/.util/host_before.sh

# Load things which must happen before the interactivity check
load_module ~/.util/before.sh

# Make sure we are running interactively, else stop
[ -z "$PS1" ] && return

clear

# Load shell options
load_module ~/.util/options.sh

# Load misc options and definitions
load_module ~/.util/after.sh

# Load host specific config
load_module ~/.util/host_after.sh

# Load things which shouldn't be checked into the public repo
load_module ~/.private.sh

# Load os specific things
load_module ~/.util/os.sh

# Load utility functions
for module in ~/.util/functions/*.sh
do
  load_module $module
done

# Load host specific functions
if [ -d ~/.util/host_functions ]; then
  for module in ~/.util/host_functions/*.sh
  do
    load_module $module
  done
fi

# Load os specific functions
if [ -d ~/.util/os_functions ]; then
  for module in ~/.util/os_functions/*.sh
  do
    load_module $module
  done
fi

# Load aliases
load_module ~/.util/aliases.sh

# Load terminal color shortcuts
load_module ~/.util/colors.sh

# Load prompt funtion
load_module ~/.util/prompt.sh

# Load auto update script
load_module ~/.util/auto_update.sh

# Load fzf
#load_module ~/.util/fzf.bash
