if [ -f ~/.bashrc ]
then
  source ~/.bashrc
fi

export GOPATH="$HOME/Code/go"
export PATH="$HOME/Code/go/bin:$HOME/Library/Haskell/bin:$HOME/.cargo/bin:$PATH"
export OPAMROOT=~/opam-coq.8.9.0
eval `opam config env`
export PATH="$PATH:$HOME/scripts"
